[package]
name = "nsc"
version = "0.3.0"
edition = "2021"
authors = ["HawkStract Labs"]
description = "The official compiler for the NodeStract (.hns) language"

[dependencies]
aes-gcm = "0.10.3"
rand = "0.8.5"
hex = "0.4.3"